package com.jonecx.qwit.model

import com.squareup.moshi.Json

data class Tweet(
    @field:Json(name = "created_at")
    val createdAt: String,
    @field:Json(name = "id")
    val id: Long,
    @field:Json(name = "id_str")
    val idStr: String,
    @field:Json(name = "text")
    val text: String,
    @field:Json(name = "truncated")
    val isTruncated: Boolean,
    @field:Json(name = "entities")
    val entities: Entities,
    @field:Json(name = "extended_entities")
    val extendedEntities: ExtendedEntities,
    @field:Json(name = "source")
    val source: String,
    @field:Json(name = "in_reply_to_status_id")
    val inReplyToStatusId: Long?,
    @field:Json(name = "in_reply_to_status_id_str")
    val inReplyToStatusIdStr: String?,
    @field:Json(name = "in_reply_to_user_id")
    val inReplyToUserId: Long?,
    @field:Json(name = "in_reply_to_user_id_str")
    val inReplyToUserIdStr: String?,
    @field:Json(name = "in_reply_to_screen_name")
    val inReplyToScreenName: String?,
    @field:Json(name = "user")
    val user: User?,
    @field:Json(name = "geo")
    val geo: Geo?,
    @field:Json(name = "coordinates")
    val coordinates: Coordinates?,
    @field:Json(name = "place")
    val place: Place?,
    @field:Json(name = "contributors")
    val contributors: String?,
    @field:Json(name = "quoted_status_id")
    val quotedStatusId: Long?,
    @field:Json(name = "quoted_status_id_str")
    val quotedStatusIdStr: String?,
    @field:Json(name = "is_quote_status")
    val isQuoteStatus: Boolean,
    @field:Json(name = "quote_count")
    val quotedCount: Int?,
    @field:Json(name = "quoted_status")
    val qoutedStatus: Tweet?,
    @field:Json(name = "reply_count")
    val replyCount: Int?,
    @field:Json(name = "retweeted_status")
    val retweetedStatus: Tweet?,
    @field:Json(name = "retweet_count")
    val retweetCount: String?,
    @field:Json(name = "favorite_count")
    val favoriteCount: Int?,
    @field:Json(name = "favorited")
    val isFavorited: Boolean,
    @field:Json(name = "retweeted")
    val isRetweeted: Boolean,
    @field:Json(name = "possibly_sensitive")
    val isSensitive: Boolean,
    @field:Json(name = "filter_level")
    val filterLevel: FilterLevel,
    @field:Json(name = "lang")
    val lang: String?,
    @field:Json(name = "matching_rules")
    val matchingRule: MatchingRule?
)
